num1=float(input("Digite um número: "))
num2=float(input("Digite outro número: "))
num3=float(input("Digite outro número: "))
res=(num1*num1)+(num2*num2)+(num3*num3)
print(f"A soma do quadrado dos três valores é: {res}")
